name: Bug report
description: File a bug
title: "Bug: "
labels: ["bug", "triage"]
body:
- type: checkboxes
  attributes:
    label: Have you read [contributing giude](../../docs/CONTRIBUTING.md)?
    options:
    - label: I have read CONTRIBUTING.md
      required: true
- type: checkboxes
  attributes:
    label: Did you check existing [bug reports](https://community.anytype.io/c/bug-reports/l/latest?board=default)?
    description: Check [this article](https://doc.anytype.io/d/community/community-forum) if you don't know how to join the community
    options:
    - label: I have searched the existing issues and didn't find any that were similar
      required: true
- type: checkboxes
  attributes:
    label: Have you considered creating a pull request with fixes instead of a bug report?
    options:
    - label: Yes, and I want to proceed with bug request
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: macOS 14
        - **Version**: 0.35.4
    value: |
        - OS:
        - Version:
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Screenshots? Videos? Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false

